# -*- coding: utf-8 -*-
"""Agent Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KD6nMwI1rdsz2gon3wkCtCeBEtLsGdIa
"""

# !pip install -U kaleido
# !pip install gradio

from openai import OpenAI
import re
import gradio as gr
import json

import plotly.graph_objects as go
from plotly.io import to_image
from PIL import Image
from io import BytesIO

def chat(messages) :

    client = OpenAI(
      base_url = "https://integrate.api.nvidia.com/v1",
      api_key = "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"
    )

    completion = client.chat.completions.create(
      model="deepseek-ai/deepseek-r1",
      messages = messages,
      temperature=0,
      # top_p=0,
      top_p=0.00001,
    # max_tokens=4096,
      stream=False
    )

    return (completion.choices[0].message.content)

msg = [{"role":"user","content":"""Who is considered to be the best clay court tennis player in history? Give me only top 3 names you can come up with.
                      Response should be in the form of List - Players - ["<Player1>", "<Player2>", "<Player3>" """}]
print (chat(msg))

def qua_ass(transcript) :
    format_instructions = """ <Result>
                                {
                                {"Header" : "Communication Skills", "Score" : "<High/Medium/Low>", "Explanation" : "<Explanation>"},
                                {"Header" : "Problem Resolution", "Score" : "<High/Medium/Low>", "Explanation" : "<Explanation>"},
                                {"Header" : "Agent Knowledge", "Score" : "<High/Medium/Low>", "Explanation" : "<Explanation>"},
                                {"Header" : "Professionalism", "Score" : "<High/Medium/Low>", "Explanation" : "<Explanation>"},
                                {"Header" : "Customer Satisfaction", "Score" : "<High/Medium/Low>", "Explanation" : "<Explanation>"},
                                {"Topics" : ["<topic1>", "<topic2>", "<topic3>"]}
                                }
                            </Result>
                            """
    # print (format_instructions)

    assessment_template = f"""
    Evaluate call transcript against categories shown below and provide score as 'High', 'Medium', 'Low' for each category and a one line explanation.
    Along with that, get the topics mentioned in the conversation.
    Skip the preamble and go straight to the answer.

    1. Communication Skills
    Clarity: To what extent does the CSR communicate information clearly and concisely to the member?
    Active Listening: Does the CSR demonstrate active listening by addressing the member’s specific concerns and questions?
    Empathy: How effectively does the CSR express empathy and understanding toward the member's situation?

    2. Problem Resolution
    Effectiveness: How successfully did the CSR resolve the member’s issue or provide accurate guidance?
    Timeliness: Was the issue addressed or resolved within an appropriate and reasonable timeframe?

    3. Agent Knowledge
    Product Understanding: Does the CSR display a strong understanding of health insurance plans, benefits, and company policies?
    Accuracy: Are the responses provided by the CSR factually correct and relevant to the member’s inquiry?

    4. Professionalism
    Tone and Demeanor: Does the CSR maintain a professional, calm, and respectful tone throughout the interaction?
    Courtesy: Is the CSR polite and respectful in their communication with the member?

    5. Customer Satisfaction
    Service Experience: How satisfied is the member likely to feel based on the quality of service provided during the call?
    Feedback Opportunity: Did the CSR invite or encourage the member to share feedback about their experience?

    Here is the call transcript:
    <transcript>{transcript}</transcript>

    Format your response per the instructions in the below format:
    {format_instructions}

    """

    # print (assessment_template)

    msg = [{"role":"system","content":"""You are a Call Center Analytics tool assessing the quality of the interaction between customer service agent and the member of health insurance"""},
          {"role":"user","content": assessment_template}]
    res = chat(msg)

    results = re.findall(r'<Result>(.*?)</Result>', res, re.DOTALL)
    res_main = str(list(results)[0])

    json_compatible = "[" + res_main.strip().strip("{}").strip() + "]"
    parsed = json.loads(json_compatible)

    print (parsed)
    return parsed

def chart(header, val):
# Data
    headers = header
    values = val
    level_map = {"Low": 1, "Medium": 2, "High": 3}
    color_map = {"Low": "#EF553B", "Medium": "#FFA15A", "High": "#00CC96"}
    numeric_values = [level_map[v] for v in values]
    bar_colors = [color_map[v] for v in values]

    # Plotly bar chart
    fig = go.Figure(data=[
        go.Bar(
            x=headers,
            y=numeric_values,
            text=values,
            textposition="outside",
            marker_color=bar_colors,
            marker_line_width=1.5
        )
    ])

    # Layout styling
    fig.update_layout(
        title="",
        plot_bgcolor="white",
        yaxis=dict(showticklabels=False, showgrid=False, zeroline=False),
        xaxis=dict(title="", tickfont=dict(size=14)),
        margin=dict(l=20, r=20, t=50, b=20),
        height=500
    )

    # Convert to image (PNG) using Kaleido
    img_bytes = to_image(fig, format="png")
    img = Image.open(BytesIO(img_bytes))
    # img.show()  # Show the image or return it in Gradio
    # img.save("plotly_bar_chart.png")
    return img

def analyze_file(file):
    # content = file.read().decode("utf-8")
    try :
        with open(file, 'r', encoding="utf-8") as fi:
            content = fi.read()
        transcript = content
    except Exception as e:
        return e

    try :
        parsed = qua_ass(transcript)

        # return parsed
        x = ''
        for i in range(5) :
            x += (parsed[i]['Header'] + ' - ' + parsed[i]['Score']  + ' | ' + parsed[i]['Explanation']) + '\n'


        # vi = ''
        # for i in range(5) :
        #     vi += (parsed[i]['Header'] + ' - ' + parsed[i]['Score']) + '\n'

        # res1, visual = viz(vi)

        header = []
        val = []
        for i in range(5) :
            # x += (parsed[i]['Header'] + ' - ' + parsed[i]['Score'] + '\n')
            header.append(parsed[i]['Header'])
            val.append(parsed[i]['Score'])

        html = chart(header, val)

        # Replace this with your actual analysis logic
        topics = ''
        if len(parsed[5]['Topics']) > 0 :
            topics += "\n".join(parsed[5]['Topics'])
        return html, x, topics
    except Exception as e :
        return (e,e, e)

file = "/content/transcript6.txt"
# print (analyze_file(file))

with gr.Blocks() as demo:
    gr.Markdown("# 📞 Agent/Call Quality Analysis")
    gr.Markdown("Upload a customer service call transcript (in `.txt` format) for automated quality evaluation.")

    with gr.Row():
        file_input = gr.File(label="Upload Transcript (.txt)", file_types=[".txt"])
        analyze_btn = gr.Button("Analyze")

    with gr.Row():
        chart_output = gr.Image(type="pil", label="Quality Analysis")
        # text_output = gr.Textbox(label="Summary", lines=4)
        with gr.Column():
            output = gr.Textbox(label="Analysis Result", lines=10)
            topics = gr.Textbox(label="Topics Overview", lines=10)

    analyze_btn.click(fn=analyze_file, inputs=file_input, outputs=[chart_output, output, topics])

demo.launch(share = True)

